---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    build: webdav-apache
  name: webdav-apache
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    build: webdav-apache
  name: webdav-apache
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'webdav-apache:latest'
      runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/codekow/webdav.git'
    contextDir: /containers/apache
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - type: ImageChange
    - type: ConfigChange