---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  labels:
    build: webdav-node
  name: webdav-node
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    build: webdav-node
  name: webdav-node
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'webdav-node:latest'
      runPolicy: Serial
  source:
    git:
      ref: main
      uri: 'https://github.com/codekow/webdav.git'
    contextDir: /containers/node
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs:latest'
        namespace: openshift
    type: Source
  triggers:
    - type: ImageChange
    - type: ConfigChange
